### ISSUE TITLE
Feature: Track owned books

### ISSUE THREAD

**Issue by sergiodxa** [codeableorg/personal-library-app#1]
**Describe the solution you'd like**
As a user, I want to track the list of books I own.

- [x] It should have a way to define the books I own.
- [x] When adding a book it should have a way to ingress how much you paid for the book. (#1)
- [x] Each book should have a cover image.
- [x] Each book should have a title.
- [x] Each book should have a resume.
- [x] Each book should have a price.
- [x] It should save the day I added it to my collection.
- [x] It should list all my owned books.
- [x] The list should show the current reading status (#2)
- [x] The list should be sortable
  - [x] By date (newest and oldest)
  - [x] By title (alphabetical and inverse)
  - [x] By reading percentage (more completed and less completed) (#2)
- [x] The list should be filterable by reading status (only pending, only reading and only completed) (#2)
