### ISSUE TITLE
Feature: Reading status

### ISSUE THREAD

**Issue by sergiodxa** [codeableorg/personal-library-app#2]
**Describe the solution you'd like**
As a user, I want to track the reading of status of my books.

- [x] Each book added to the user collection should have a reading status.
- [x] The books should be on `pending` by default.
- [x] After it's marked on `reading` it should save the current page.
- [x] Using the current page it should calculate the progress in a percentage.
- [x] After `completed` the current page should be changed to the total of pages.
- [x] The current status should be displayed on the list (#1).
- [x] The list of books should be filterable by status (only pending, only reading and only completed) (#1)
- [x] The list of books should be sortable by reading percentage (#1)
